name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build-validation:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      CI: true

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node LTS version
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn eslint .

      - name: Test
        if: startsWith(matrix.os, 'windows')
        run: yarn test

      - name: Test
        if: startsWith(matrix.os, 'ubuntu')
        run: yarn coverage

      - name: Coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: startsWith(matrix.os, 'ubuntu') && github.event_name == 'pull_request'
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          indicators: true
          output: both

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v3.0.4
        if: startsWith(matrix.os, 'ubuntu') && github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
