name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-validation:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node LTS version
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn eslint .

      - name: Test
        if: startsWith(matrix.os, 'windows')
        run: yarn test

      - name: Test
        if: startsWith(matrix.os, 'ubuntu')
        run: yarn coverage
